name: Test Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
      
    - name: Upload Test log
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
       name: screenshots
       path: screenshots/


    - name: Upload HTML Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.1
      with:
       name: html-report
       path: report.html

    - name: Test Execution status
      if: always()
      run:  echo "Test Execution Completed"
      
    









    
